version: 2

repo:
  public: ruby-server-sdk
  private: ruby-server-sdk-private

branches:
  - name: master
  - name: 5.x

publications:
  - url: https://rubygems.org/gems/launchdarkly-server-sdk
    description: RubyGems
  - url: https://www.rubydoc.info/gems/launchdarkly-server-sdk
    description: documentation

jobs:
  - docker:
      image: ruby:2.5-buster
      copyGitHistory: true  # building gem requires git metadata due to use of "git ls-files" in the gemspec
    template:
      name: ruby
    env:
      LD_SKIP_DATABASE_TESTS: "1"  # Don't run Redis/Consul/DynamoDB tests in release; they are run in CI

documentation:
  gitHubPages: true

sdk:
  displayName: "Ruby"
